# Generated by Django 2.0.7 on 2018-08-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=350)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=400)),
                ('university', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=700)),
                ('essay', models.CharField(max_length=750)),
                ('resume', models.FileField(upload_to='')),
                ('cover_letter', models.FileField(upload_to='')),
            ],
        ),
    ]
